language: rust
rust: stable
sudo: false
dist: trusty

cache: yarn

before_install:
  - nvm install 6.10.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - yarn
  - yarn run bower install
  - cargo install diesel_cli --debug --no-default-features --features postgres && export PATH=$HOME/.cargo/bin:$PATH

before_script:
  - diesel database setup

script:
  - cargo build
  - cargo test
  - yarn run test

after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  include:
  - rust: nightly-2017-03-04
    env: CLIPPY=YESPLEASE
    script:
    - cargo rustc --lib --features "lint" -- -Zno-trans

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test

notifications:
  email:
    on_success: never
