language: rust
rust: nightly
sudo: false

cache: yarn

before_install:
  - nvm install 4.6.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - yarn
  - yarn run bower install

before_script:
  - psql -c 'create database cargo_registry_test;' -U postgres

script:
  - cargo build
  - cargo test
  - yarn run test

after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.3"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

notifications:
  email:
    on_success: never
