[package]
name = "conduit-hyper"
version = "0.4.2"
authors = ["Justin Geibel <jtgeibel@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Host a conduit based web application on a hyper server"
readme = "README.md"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
bytes = "=1.3.0"
conduit = "0.10.0"
hyper = { version = "=0.14.23", features = ["server", "http1", "stream", "tcp"] }
http = "=0.2.8"
percent-encoding = "=2.2.0"
thiserror = "=1.0.37"
tracing = "=0.1.37"
tokio = { version = "=1.23.0", features = ["fs"] }
tokio-stream = "=0.1.11"
tower-service = "=0.3.2"

[dev-dependencies]
conduit-router = "0.10.0"
futures-util = "=0.3.25"
hyper = { version = "=0.14.23", features = ["client"] }
tokio = { version = "=1.23.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "=0.3.16"
