[package]
name = "crates_io_tarball"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
builder = []

[dependencies]
derive_deref = "=1.1.1"
flate2 = "=1.0.26"
semver = { version = "=1.0.17", features = ["serde"] }
serde = { version = "=1.0.171", features = ["derive"] }
serde_json = "=1.0.102"
tar = "=0.4.39"
thiserror = "=1.0.43"
toml = "=0.7.6"
tracing = "=0.1.37"

[dev-dependencies]
anyhow = "=1.0.71"
claims = "=0.7.1"
clap = { version = "=4.3.11", features = ["derive", "unicode", "wrap_help"] }
tracing-subscriber = { version = "=0.3.17", features = ["env-filter"] }
