[package]
name = "crates_io_smoke_test"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap = { workspace = true, features = ["derive", "env", "unicode", "wrap_help"] }
crates_io_index.workspace = true
reqwest = { workspace = true, features = ["blocking", "gzip", "json"] }
secrecy.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
