[package]
name = "crates_io_worker"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "=1.0.75"
async-trait = "=0.1.74"
diesel = { version = "=2.1.4", features = ["postgres", "r2d2", "serde_json"] }
futures-util = "=0.3.29"
sentry-core = { version = "=0.31.8", features = ["client"] }
serde = { version = "=1.0.193", features = ["derive"] }
serde_json = "=1.0.108"
thiserror = "=1.0.50"
tokio = { version = "=1.35.0", features = ["rt"]}
tracing = "=0.1.40"

[dev-dependencies]
crates_io_test_db = { path = "../crates_io_test_db" }
tokio = { version = "=1.35.0", features = ["macros", "rt", "sync"]}
