[package]
name = "tools"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "crates.io tools for common maintenance tasks"
edition = "2018"

[dependencies]
cargo-registry = { path = "../cargo-registry" }
diesel = { version = "1.4.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
